redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "D:\\Coding Projects\\Hajj Website\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
base = "D:\\Coding Projects\\Hajj Website\\frontend"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]